todo_app/models.py
from .extensions import db
from datetime import datetime as dt


class Task(db.Model):
    __tablename__='task'
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(255), nullable=False)
    date_time_ = db.Column(db.DateTime, nullable=False, default=dt.now)

    def __repr__(self):
        return f'Task: {self.text}'

todo_app/__init__.py
from flask import Flask
from .extensions import db, migrate
# from .credentials import *
import os

def create_app():

    random_key = os.urandom(16)

    app = Flask(__name__)

    app.config.from_mapping(
        SECRET_KEY=random_key,
        SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db',
        SQLALCHEMY_TRACK_MODIFICATIONS=False,
    )

    db.init_app(app)
    migrate.init_app(app, db)
    
    with app.app_context():
        db.create_all()
        print('Initialized database...')

    @app.route('/todo')
    def test():
        return "Testing my todo app..."

    from .routes.index import bp
    app.register_blueprint(bp)
    
    from .routes.create import create_bp
    app.register_blueprint(create_bp)
    
    from .routes.edit import edit_bp
    app.register_blueprint(edit_bp)
    
    from .routes.delete import delete_bp
    app.register_blueprint(delete_bp)

    return app

create_app()

todo_app/routes/create.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    flash,
    request
    )

from ..models import Task
from ..extensions import db

create_bp = Blueprint('create', __name__)

@create_bp.route('/todo/add', methods=['GET', 'POST'])
def add():

    if request.method == 'POST':
        error = None

        text = request.form['task']

        if not text:
            error = 'This space cannot be empty.'
        if error is not None:
            flash(error)
        else:
            task = Task(text=text)

            db.session.add(task)
            db.session.commit()
            return redirect(url_for('index.main'))

    return render_template('index.html')

todo_app/routes/delete.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    flash,
    request
    )

from ..models import Task
from ..extensions import db

delete_bp = Blueprint('delete', __name__)


@delete_bp.route('/todo/delete/<int:id>/')
def delete(id):
    get_task = Task.query.filter_by(id=id).one()
    db.session.delete(get_task)
    db.session.commit()
    return redirect(url_for('index.main'))

todo_app/routes/edit.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    flash,
    request
    )

from ..models import Task
from ..extensions import db

edit_bp = Blueprint('edit', __name__)

@edit_bp.route('/todo/<int:id>/edit')
def render_edit(id):

    task = Task.query.filter_by(id=id).one()

    return render_template('edit.html', task=task)


@edit_bp.route('/edit/<int:id>/', methods=['GET', 'POST'])
def edit(id):
    task = Task.query.filter_by(id=id).one()

    if request.method == 'POST':
        error = None

        edit_task = request.form['edit']

        if not edit_task:
            error = 'This space cannot be empty.'

        if error is not None:
            flash(error)
        else:
            task.text = edit_task
            db.session.commit()
            return redirect(url_for('index.main'))

    return render_template('edit.html', task=task)

todo_app/routes/index.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    flash,
    request
    )

from ..models import Task
from ..extensions import db

bp = Blueprint('index', __name__)


@bp.route('/')
def main():
    tasks = Task.query.all()
    return render_template('index.html', tasks=tasks)

todo_app/templates/edit.html
{% extends 'main.html' %}

{% block head %} {{ super() }} {% endblock %}

{% block title %} Edit task - {{ task.id }} {% endblock %}

{% block content %}
  <header>
    <nav>
      <p>TODO</p>
    </nav>
  </header>

  <main>
    <section>

      <div class="container">
        <h1 class='task-id'>Edit Task {{ task.id }}</h1>
        {% for message in get_flashed_messages() %}
        <div class="message">{{ message }}</div>
        {% endfor %}

          {% if task %}
          <div class="form-edit">
            <form action="{{ url_for('edit.edit', id=task.id) }}" method="post">
              <input type="text" name="edit" value="{{ task.text or request.form['edit'] }}">
              <input type="submit" value="ADD">
              <button class='submit'><a href="{{ url_for('index.main') }}">Cancel</a></button>
            </form>
          </div>
          {% endif %}
      </div>

    </section>
  </main>
{% endblock %}

todo_app/templates/index.html
{% extends 'main.html' %}

{% block head %} {{ super() }} {% endblock %}

{% block title %} My TODO APP {% endblock %}

{% block content %}
  <header>
    <nav>
      <p>TODO</p>
    </nav>
  </header>

  <main>
    <section>

      <div class="btn-task">
        <i class="fa-2x bi bi-plus-circle-fill"></i></span>
      </div>

      <div class="container">

        <div class="form">
          <form action="{{ url_for('create.add') }}" method="post">
            <input type="text" name="task" placeholder=" Write your task">
            <input class='submit' type="submit" value="Add">
            <button class='submit'><a href="{{ url_for('index.main') }}">Cancel</a></button>
          </form>
        </div>

        {% for message in get_flashed_messages() %}
        <div class="message">{{ message }}</div>
        {% endfor %}

        {% for task in tasks %}
        <div class="task-wrapper">
          <p class="date">{{ task.date_time_.strftime('%A, %B %d %Y') }}</p>
          <div class="task">
            <p>{{ task.text }}</p>
            <p class="para-time">{{ task.date_time_.strftime('%H:%M') }}</p>
            <a href="{{ url_for('edit.render_edit', id=task.id) }}">Edit</a>
            <a href="{{ url_for('delete.delete', id=task.id) }}">Delete</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </section>
  </main>
{% endblock %}

todo_app/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" type="text/css" media="all" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500&family=Ubuntu:wght@400;500&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
  {% endblock %}
</head>
<body>
  {% block content %}{% endblock %}
  <script type="text/javascript" src="{{ url_for('static', filename='script/jquery.min.js') }}" charset="utf-8"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='script/script.js') }}" charset="utf-8"></script>
</body>
</html>